// Mocks generated by Mockito 5.4.5 from annotations
// in resto_dicodingsubs/test/unit_test/restaurant_list_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:resto_dicodingsubs/api/api_service.dart' as _i3;
import 'package:resto_dicodingsubs/model/restaurant_response.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestoResponse_0 extends _i1.SmartFake implements _i2.RestoResponse {
  _FakeRestoResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RestoResponse> getRestaurants() => (super.noSuchMethod(
        Invocation.method(#getRestaurants, []),
        returnValue: _i4.Future<_i2.RestoResponse>.value(
          _FakeRestoResponse_0(
            this,
            Invocation.method(#getRestaurants, []),
          ),
        ),
      ) as _i4.Future<_i2.RestoResponse>);

  @override
  _i4.Future<_i2.RestoResponse> getRestaurantDetail(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#getRestaurantDetail, [id]),
        returnValue: _i4.Future<_i2.RestoResponse>.value(
          _FakeRestoResponse_0(
            this,
            Invocation.method(#getRestaurantDetail, [id]),
          ),
        ),
      ) as _i4.Future<_i2.RestoResponse>);

  @override
  String getImageUrl(String? pictureId, _i3.ImageSize? size) =>
      (super.noSuchMethod(
        Invocation.method(#getImageUrl, [pictureId, size]),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(#getImageUrl, [pictureId, size]),
        ),
      ) as String);

  @override
  _i4.Future<_i2.RestoResponse> postReview(
    String? id,
    String? name,
    String? review,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#postReview, [id, name, review]),
        returnValue: _i4.Future<_i2.RestoResponse>.value(
          _FakeRestoResponse_0(
            this,
            Invocation.method(#postReview, [id, name, review]),
          ),
        ),
      ) as _i4.Future<_i2.RestoResponse>);

  @override
  _i4.Future<_i2.RestoResponse> searchRestaurants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchRestaurants, [query]),
        returnValue: _i4.Future<_i2.RestoResponse>.value(
          _FakeRestoResponse_0(
            this,
            Invocation.method(#searchRestaurants, [query]),
          ),
        ),
      ) as _i4.Future<_i2.RestoResponse>);
}
